name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Set up JDK (required by SonarScanner)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Begin SonarQube analysis
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"SonarGit" `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
            /d:sonar.cs.opencover.reportsPaths="coverage/**/coverage.cobertura.xml"

      - name: Build
        run: dotnet build

      - name: Run tests (optional, for coverage)
        continue-on-error: true
        run: |
          mkdir coverage
          dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory coverage

      - name: End SonarQube analysis
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end `
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
